### PR TITLE
Remove unused webkit dependencies

### PR DESCRIPTION
**Pull request by TingPing**
These aren't used in flatpak

### CODE REVIEW

**Comment by bbhtt** [comment]
Can you also update the version and the x-checker, please? It's bundling an outdated copy when it receives quite the number of security fixes each release.

https://github.com/flathub/com.amazon.Workspaces/blob/a72f7e2df80013c7a5ba0da5912161bf6d1e3140/com.amazon.Workspaces.yml#L49-L98

**Comment by camelCaseNick** [comment]
@TingPing Is there any documentation saying that it doesn't use bubblewrap within the flatpak bubblewrap?

**Comment by bbhtt** [comment]
I don't think there is, but you can check the code. The sandbox is only used if it is not inside snap, flatpak or an unsupported container https://github.com/WebKit/WebKit/blob/45dd419f3fea1f19ac6e03c71faad7533eb77cd2/Source/WebKit/UIProcess/Launcher/glib/ProcessLauncherGLib.cpp#L225

`isInsideFlatpak` checks for the existence of `/.flatpak-info` 

@TingPing is also a webkitgtk dev so they can expand on the specifics more.

**Comment by TingPing** [comment]
@bbhtt nailed it. Also a few lines up you will see it uses `flatpak-spawn` to do sandboxing:

```c++
    if (sandboxEnabled && isFlatpakSpawnUsable())
        process = flatpakSpawn(...)
```

**Comment by camelCaseNick** [comment]
Thank You!

**Comment by TingPing** [comment]
> Can you also update the version and the x-checker, please? It's bundling an outdated copy when it receives quite the number of security fixes each release.

Untested but done.

**Pull request merged**
